### ISSUE TITLE
BUG: Wrong signature for write() function.

### ISSUE THREAD

**Issue by StasD** [DxCx/ts-xlsx#10] opened 2017-02-25 15:20 UTC
The @types/xlsx project (which your project is dependent upon) uses the following signature for the write() function:
`export declare function write(data: any, opts?: IParsingOptions): any;`

Note that the opts parameter has the same type as one in the read() function:
`export declare function read(data: any, opts?: IParsingOptions): IWorkBook;`

Which is WRONG:
https://github.com/SheetJS/js-xlsx#writing-options

Now I'm getting errors when I try to pass an options object with e.g. `bookSST` property...

And white we are at it... I really hate the idea of types in Javascript (and elsewhere, really)...
And this bug is just an example that they don't solve any problems, but rather create new ones, and make things more complicated...

**Comment by DxCx** [comment] 2017-03-03 05:38
Hey @StasD, sorry for the late response i was on vacation with limited connectivity..

If you dont like the idea of typings, you can always use raw javascript, i myself think that types are needed, the problem is that not all typings are managed correctly..

Anyway, @types/xlsx is not under my control but also open under DefinitlyTyped, i suggest you to open a PR there fixing it and we will update the dependency here as well...

**Comment by StasD** [comment] 2017-03-03 06:17
Thanks, @DxCx! Will do.

We use Angular 2 with TypeScript at work. So have to use types... :)
When I try using xlsx library directly, I'm getting errors while building the site with angular cli...
For now, I settled with using default settings for the 2 parameters (`bookSST` and `compression`) which I initially wanted to set to `true`. This way it works, though it's not ideal.

**Comment by DxCx** [comment] 2017-03-04 07:00
Alright :)

**Comment by DxCx** [comment] 2017-04-15 20:16
Closed by DefinitelyTyped/DefinitelyTyped#15129

**Closed as completed by DxCx** 2017-04-15 20:16 UTC

**Comment by StasD** [comment] 2017-04-16 05:20
Hello, @DxCx,
I think you need to make changes to "ts-xlsx", as I still cannot compile the project if I add "bookSST: true" and "compression: true" to options...
I checked your package.json file, and found that it has "@types/xlsx": "0.0.32" in "dependencies" section. And while I do have "0.0.33" version specified in my package.json, it seems the compiler ignores it and uses the dependency as requested by "@types/xlsx". It probably also means that I don't need separate "@types/xlsx" at all...

**Comment by StasD** [comment] 2017-04-16 05:55
And it looks like it uses your "xlsx", specified as "xlsx": "^0.8.3", as well...
So it will stuck at 0.8.8, as latest in 0.8.x line, while the latest version of xlsx is already 0.9.10.
But along with updating versions, maybe it is better to also move "xlsx" and "@types/xlsx" into "peerDependencies" section since in the docs you are asking to install these anyway?

**Comment by DxCx** [comment] 2017-04-16 08:51
Hey can you open a PR?
It wont work as peerDependancy as this packe rebundles xlsx so it will be able to run im browser..

**Comment by StasD** [comment] 2017-04-16 09:14
OK... :) Done.
"npm run build", "npm run test", "npm run pack" all seem to be working.

**Comment by StasD** [comment] 2017-04-16 09:22
Also gave you a star. :)

**Comment by DxCx** [comment] 2017-04-16 10:15
Cool thanks, will be looking at it later today :)
